/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ring.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ring.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Ring_L.geometry} material={materials.blinn1} />
    </group>
  )
}

useGLTF.preload('/ring.gltf')
